name: Autograding

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check file exists
        run: test -f centos-installation.md

      - name: Check content
        run: grep -i "VirtualBox" centos-installation.md